INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (1, 'AF', 'AFG', 4, 93, 'AFGHANISTAN', 'Afghanistan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (2, 'AL', 'ALB', 8, 355, 'ALBANIA', 'Albania');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (3, 'DZ', 'DZA', 12, 213, 'ALGERIA', 'Algeria');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (4, 'AS', 'ASM', 16, 1684, 'AMERICAN SAMOA', 'American Samoa');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (5, 'AD', 'AND', 20, 376, 'ANDORRA', 'Andorra');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (6, 'AO', 'AGO', 24, 244, 'ANGOLA', 'Angola');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (7, 'AI', 'AIA', 660, 1264, 'ANGUILLA', 'Anguilla');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (8, 'AQ', null, null, 0, 'ANTARCTICA', 'Antarctica');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (9, 'AG', 'ATG', 28, 1268, 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (10, 'AR', 'ARG', 32, 54, 'ARGENTINA', 'Argentina');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (11, 'AM', 'ARM', 51, 374, 'ARMENIA', 'Armenia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (12, 'AW', 'ABW', 533, 297, 'ARUBA', 'Aruba');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (13, 'AU', 'AUS', 36, 61, 'AUSTRALIA', 'Australia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (14, 'AT', 'AUT', 40, 43, 'AUSTRIA', 'Austria');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (15, 'AZ', 'AZE', 31, 994, 'AZERBAIJAN', 'Azerbaijan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (16, 'BS', 'BHS', 44, 1242, 'BAHAMAS', 'Bahamas');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (17, 'BH', 'BHR', 48, 973, 'BAHRAIN', 'Bahrain');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (18, 'BD', 'BGD', 50, 880, 'BANGLADESH', 'Bangladesh');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (19, 'BB', 'BRB', 52, 1246, 'BARBADOS', 'Barbados');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (20, 'BY', 'BLR', 112, 375, 'BELARUS', 'Belarus');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (21, 'BE', 'BEL', 56, 32, 'BELGIUM', 'Belgium');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (22, 'BZ', 'BLZ', 84, 501, 'BELIZE', 'Belize');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (23, 'BJ', 'BEN', 204, 229, 'BENIN', 'Benin');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (24, 'BM', 'BMU', 60, 1441, 'BERMUDA', 'Bermuda');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (25, 'BT', 'BTN', 64, 975, 'BHUTAN', 'Bhutan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (26, 'BO', 'BOL', 68, 591, 'BOLIVIA', 'Bolivia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (27, 'BA', 'BIH', 70, 387, 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (28, 'BW', 'BWA', 72, 267, 'BOTSWANA', 'Botswana');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (29, 'BV', null, null, 0, 'BOUVET ISLAND', 'Bouvet Island');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (30, 'BR', 'BRA', 76, 55, 'BRAZIL', 'Brazil');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (31, 'IO', null, null, 246, 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (32, 'BN', 'BRN', 96, 673, 'BRUNEI DARUSSALAM', 'Brunei Darussalam');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (33, 'BG', 'BGR', 100, 359, 'BULGARIA', 'Bulgaria');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (34, 'BF', 'BFA', 854, 226, 'BURKINA FASO', 'Burkina Faso');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (35, 'BI', 'BDI', 108, 257, 'BURUNDI', 'Burundi');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (36, 'KH', 'KHM', 116, 855, 'CAMBODIA', 'Cambodia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (37, 'CM', 'CMR', 120, 237, 'CAMEROON', 'Cameroon');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (38, 'CA', 'CAN', 124, 1, 'CANADA', 'Canada');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (39, 'CV', 'CPV', 132, 238, 'CAPE VERDE', 'Cape Verde');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (40, 'KY', 'CYM', 136, 1345, 'CAYMAN ISLANDS', 'Cayman Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (41, 'CF', 'CAF', 140, 236, 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (42, 'TD', 'TCD', 148, 235, 'CHAD', 'Chad');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (43, 'CL', 'CHL', 152, 56, 'CHILE', 'Chile');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (44, 'CN', 'CHN', 156, 86, 'CHINA', 'China');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (45, 'CX', null, null, 61, 'CHRISTMAS ISLAND', 'Christmas Island');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (46, 'CC', null, null, 672, 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (47, 'CO', 'COL', 170, 57, 'COLOMBIA', 'Colombia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (48, 'KM', 'COM', 174, 269, 'COMOROS', 'Comoros');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (49, 'CG', 'COG', 178, 242, 'CONGO', 'Congo');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (50, 'CD', 'COD', 180, 242, 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (51, 'CK', 'COK', 184, 682, 'COOK ISLANDS', 'Cook Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (52, 'CR', 'CRI', 188, 506, 'COSTA RICA', 'Costa Rica');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (53, 'CI', 'CIV', 384, 225, 'COTE D\'IVOIRE', 'Cote D\'Ivoire');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (54, 'HR', 'HRV', 191, 385, 'CROATIA', 'Croatia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (55, 'CU', 'CUB', 192, 53, 'CUBA', 'Cuba');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (56, 'CY', 'CYP', 196, 357, 'CYPRUS', 'Cyprus');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (57, 'CZ', 'CZE', 203, 420, 'CZECH REPUBLIC', 'Czech Republic');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (58, 'DK', 'DNK', 208, 45, 'DENMARK', 'Denmark');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (59, 'DJ', 'DJI', 262, 253, 'DJIBOUTI', 'Djibouti');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (60, 'DM', 'DMA', 212, 1767, 'DOMINICA', 'Dominica');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (61, 'DO', 'DOM', 214, 1809, 'DOMINICAN REPUBLIC', 'Dominican Republic');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (62, 'EC', 'ECU', 218, 593, 'ECUADOR', 'Ecuador');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (63, 'EG', 'EGY', 818, 20, 'EGYPT', 'Egypt');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (64, 'SV', 'SLV', 222, 503, 'EL SALVADOR', 'El Salvador');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (65, 'GQ', 'GNQ', 226, 240, 'EQUATORIAL GUINEA', 'Equatorial Guinea');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (66, 'ER', 'ERI', 232, 291, 'ERITREA', 'Eritrea');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (67, 'EE', 'EST', 233, 372, 'ESTONIA', 'Estonia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (68, 'ET', 'ETH', 231, 251, 'ETHIOPIA', 'Ethiopia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (69, 'FK', 'FLK', 238, 500, 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (70, 'FO', 'FRO', 234, 298, 'FAROE ISLANDS', 'Faroe Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (71, 'FJ', 'FJI', 242, 679, 'FIJI', 'Fiji');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (72, 'FI', 'FIN', 246, 358, 'FINLAND', 'Finland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (73, 'FR', 'FRA', 250, 33, 'FRANCE', 'France');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (74, 'GF', 'GUF', 254, 594, 'FRENCH GUIANA', 'French Guiana');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (75, 'PF', 'PYF', 258, 689, 'FRENCH POLYNESIA', 'French Polynesia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (76, 'TF', null, null, 0, 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (77, 'GA', 'GAB', 266, 241, 'GABON', 'Gabon');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (78, 'GM', 'GMB', 270, 220, 'GAMBIA', 'Gambia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (79, 'GE', 'GEO', 268, 995, 'GEORGIA', 'Georgia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (80, 'DE', 'DEU', 276, 49, 'GERMANY', 'Germany');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (81, 'GH', 'GHA', 288, 233, 'GHANA', 'Ghana');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (82, 'GI', 'GIB', 292, 350, 'GIBRALTAR', 'Gibraltar');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (83, 'GR', 'GRC', 300, 30, 'GREECE', 'Greece');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (84, 'GL', 'GRL', 304, 299, 'GREENLAND', 'Greenland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (85, 'GD', 'GRD', 308, 1473, 'GRENADA', 'Grenada');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (86, 'GP', 'GLP', 312, 590, 'GUADELOUPE', 'Guadeloupe');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (87, 'GU', 'GUM', 316, 1671, 'GUAM', 'Guam');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (88, 'GT', 'GTM', 320, 502, 'GUATEMALA', 'Guatemala');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (89, 'GN', 'GIN', 324, 224, 'GUINEA', 'Guinea');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (90, 'GW', 'GNB', 624, 245, 'GUINEA-BISSAU', 'Guinea-Bissau');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (91, 'GY', 'GUY', 328, 592, 'GUYANA', 'Guyana');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (92, 'HT', 'HTI', 332, 509, 'HAITI', 'Haiti');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (93, 'HM', null, null, 0, 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (94, 'VA', 'VAT', 336, 39, 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (95, 'HN', 'HND', 340, 504, 'HONDURAS', 'Honduras');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (96, 'HK', 'HKG', 344, 852, 'HONG KONG', 'Hong Kong');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (97, 'HU', 'HUN', 348, 36, 'HUNGARY', 'Hungary');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (98, 'IS', 'ISL', 352, 354, 'ICELAND', 'Iceland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (99, 'IN', 'IND', 356, 91, 'INDIA', 'India');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (100, 'ID', 'IDN', 360, 62, 'INDONESIA', 'Indonesia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (101, 'IR', 'IRN', 364, 98, 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (102, 'IQ', 'IRQ', 368, 964, 'IRAQ', 'Iraq');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (103, 'IE', 'IRL', 372, 353, 'IRELAND', 'Ireland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (104, 'IL', 'ISR', 376, 972, 'ISRAEL', 'Israel');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (105, 'IT', 'ITA', 380, 39, 'ITALY', 'Italy');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (106, 'JM', 'JAM', 388, 1876, 'JAMAICA', 'Jamaica');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (107, 'JP', 'JPN', 392, 81, 'JAPAN', 'Japan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (108, 'JO', 'JOR', 400, 962, 'JORDAN', 'Jordan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (109, 'KZ', 'KAZ', 398, 7, 'KAZAKHSTAN', 'Kazakhstan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (110, 'KE', 'KEN', 404, 254, 'KENYA', 'Kenya');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (111, 'KI', 'KIR', 296, 686, 'KIRIBATI', 'Kiribati');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (112, 'KP', 'PRK', 408, 850, 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'Korea, Democratic People\'s Republic of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (113, 'KR', 'KOR', 410, 82, 'KOREA, REPUBLIC OF', 'Korea, Republic of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (114, 'KW', 'KWT', 414, 965, 'KUWAIT', 'Kuwait');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (115, 'KG', 'KGZ', 417, 996, 'KYRGYZSTAN', 'Kyrgyzstan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (116, 'LA', 'LAO', 418, 856, 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'Lao People\'s Democratic Republic');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (117, 'LV', 'LVA', 428, 371, 'LATVIA', 'Latvia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (118, 'LB', 'LBN', 422, 961, 'LEBANON', 'Lebanon');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (119, 'LS', 'LSO', 426, 266, 'LESOTHO', 'Lesotho');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (120, 'LR', 'LBR', 430, 231, 'LIBERIA', 'Liberia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (121, 'LY', 'LBY', 434, 218, 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (122, 'LI', 'LIE', 438, 423, 'LIECHTENSTEIN', 'Liechtenstein');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (123, 'LT', 'LTU', 440, 370, 'LITHUANIA', 'Lithuania');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (124, 'LU', 'LUX', 442, 352, 'LUXEMBOURG', 'Luxembourg');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (125, 'MO', 'MAC', 446, 853, 'MACAO', 'Macao');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (126, 'MK', 'MKD', 807, 389, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (127, 'MG', 'MDG', 450, 261, 'MADAGASCAR', 'Madagascar');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (128, 'MW', 'MWI', 454, 265, 'MALAWI', 'Malawi');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (129, 'MY', 'MYS', 458, 60, 'MALAYSIA', 'Malaysia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (130, 'MV', 'MDV', 462, 960, 'MALDIVES', 'Maldives');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (131, 'ML', 'MLI', 466, 223, 'MALI', 'Mali');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (132, 'MT', 'MLT', 470, 356, 'MALTA', 'Malta');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (133, 'MH', 'MHL', 584, 692, 'MARSHALL ISLANDS', 'Marshall Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (134, 'MQ', 'MTQ', 474, 596, 'MARTINIQUE', 'Martinique');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (135, 'MR', 'MRT', 478, 222, 'MAURITANIA', 'Mauritania');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (136, 'MU', 'MUS', 480, 230, 'MAURITIUS', 'Mauritius');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (137, 'YT', null, null, 269, 'MAYOTTE', 'Mayotte');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (138, 'MX', 'MEX', 484, 52, 'MEXICO', 'Mexico');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (139, 'FM', 'FSM', 583, 691, 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (140, 'MD', 'MDA', 498, 373, 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (141, 'MC', 'MCO', 492, 377, 'MONACO', 'Monaco');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (142, 'MN', 'MNG', 496, 976, 'MONGOLIA', 'Mongolia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (143, 'MS', 'MSR', 500, 1664, 'MONTSERRAT', 'Montserrat');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (144, 'MA', 'MAR', 504, 212, 'MOROCCO', 'Morocco');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (145, 'MZ', 'MOZ', 508, 258, 'MOZAMBIQUE', 'Mozambique');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (146, 'MM', 'MMR', 104, 95, 'MYANMAR', 'Myanmar');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (147, 'NA', 'NAM', 516, 264, 'NAMIBIA', 'Namibia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (148, 'NR', 'NRU', 520, 674, 'NAURU', 'Nauru');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (149, 'NP', 'NPL', 524, 977, 'NEPAL', 'Nepal');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (150, 'NL', 'NLD', 528, 31, 'NETHERLANDS', 'Netherlands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (151, 'AN', 'ANT', 530, 599, 'NETHERLANDS ANTILLES', 'Netherlands Antilles');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (152, 'NC', 'NCL', 540, 687, 'NEW CALEDONIA', 'New Caledonia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (153, 'NZ', 'NZL', 554, 64, 'NEW ZEALAND', 'New Zealand');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (154, 'NI', 'NIC', 558, 505, 'NICARAGUA', 'Nicaragua');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (155, 'NE', 'NER', 562, 227, 'NIGER', 'Niger');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (156, 'NG', 'NGA', 566, 234, 'NIGERIA', 'Nigeria');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (157, 'NU', 'NIU', 570, 683, 'NIUE', 'Niue');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (158, 'NF', 'NFK', 574, 672, 'NORFOLK ISLAND', 'Norfolk Island');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (159, 'MP', 'MNP', 580, 1670, 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (160, 'NO', 'NOR', 578, 47, 'NORWAY', 'Norway');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (161, 'OM', 'OMN', 512, 968, 'OMAN', 'Oman');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (162, 'PK', 'PAK', 586, 92, 'PAKISTAN', 'Pakistan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (163, 'PW', 'PLW', 585, 680, 'PALAU', 'Palau');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (164, 'PS', null, null, 970, 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (165, 'PA', 'PAN', 591, 507, 'PANAMA', 'Panama');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (166, 'PG', 'PNG', 598, 675, 'PAPUA NEW GUINEA', 'Papua New Guinea');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (167, 'PY', 'PRY', 600, 595, 'PARAGUAY', 'Paraguay');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (168, 'PE', 'PER', 604, 51, 'PERU', 'Peru');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (169, 'PH', 'PHL', 608, 63, 'PHILIPPINES', 'Philippines');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (170, 'PN', 'PCN', 612, 0, 'PITCAIRN', 'Pitcairn');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (171, 'PL', 'POL', 616, 48, 'POLAND', 'Poland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (172, 'PT', 'PRT', 620, 351, 'PORTUGAL', 'Portugal');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (173, 'PR', 'PRI', 630, 1787, 'PUERTO RICO', 'Puerto Rico');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (174, 'QA', 'QAT', 634, 974, 'QATAR', 'Qatar');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (175, 'RE', 'REU', 638, 262, 'REUNION', 'Reunion');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (176, 'RO', 'ROM', 642, 40, 'ROMANIA', 'Romania');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (177, 'RU', 'RUS', 643, 70, 'RUSSIAN FEDERATION', 'Russian Federation');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (178, 'RW', 'RWA', 646, 250, 'RWANDA', 'Rwanda');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (179, 'SH', 'SHN', 654, 290, 'SAINT HELENA', 'Saint Helena');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (180, 'KN', 'KNA', 659, 1869, 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (181, 'LC', 'LCA', 662, 1758, 'SAINT LUCIA', 'Saint Lucia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (182, 'PM', 'SPM', 666, 508, 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (183, 'VC', 'VCT', 670, 1784, 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (184, 'WS', 'WSM', 882, 684, 'SAMOA', 'Samoa');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (185, 'SM', 'SMR', 674, 378, 'SAN MARINO', 'San Marino');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (186, 'ST', 'STP', 678, 239, 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (187, 'SA', 'SAU', 682, 966, 'SAUDI ARABIA', 'Saudi Arabia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (188, 'SN', 'SEN', 686, 221, 'SENEGAL', 'Senegal');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (189, 'CS', null, null, 381, 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (190, 'SC', 'SYC', 690, 248, 'SEYCHELLES', 'Seychelles');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (191, 'SL', 'SLE', 694, 232, 'SIERRA LEONE', 'Sierra Leone');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (192, 'SG', 'SGP', 702, 65, 'SINGAPORE', 'Singapore');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (193, 'SK', 'SVK', 703, 421, 'SLOVAKIA', 'Slovakia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (194, 'SI', 'SVN', 705, 386, 'SLOVENIA', 'Slovenia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (195, 'SB', 'SLB', 90, 677, 'SOLOMON ISLANDS', 'Solomon Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (196, 'SO', 'SOM', 706, 252, 'SOMALIA', 'Somalia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (197, 'ZA', 'ZAF', 710, 27, 'SOUTH AFRICA', 'South Africa');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (198, 'GS', null, null, 0, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (199, 'ES', 'ESP', 724, 34, 'SPAIN', 'Spain');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (200, 'LK', 'LKA', 144, 94, 'SRI LANKA', 'Sri Lanka');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (201, 'SD', 'SDN', 736, 249, 'SUDAN', 'Sudan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (202, 'SR', 'SUR', 740, 597, 'SURINAME', 'Suriname');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (203, 'SJ', 'SJM', 744, 47, 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (204, 'SZ', 'SWZ', 748, 268, 'SWAZILAND', 'Swaziland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (205, 'SE', 'SWE', 752, 46, 'SWEDEN', 'Sweden');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (206, 'CH', 'CHE', 756, 41, 'SWITZERLAND', 'Switzerland');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (207, 'SY', 'SYR', 760, 963, 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (208, 'TW', 'TWN', 158, 886, 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (209, 'TJ', 'TJK', 762, 992, 'TAJIKISTAN', 'Tajikistan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (210, 'TZ', 'TZA', 834, 255, 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (211, 'TH', 'THA', 764, 66, 'THAILAND', 'Thailand');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (212, 'TL', null, null, 670, 'TIMOR-LESTE', 'Timor-Leste');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (213, 'TG', 'TGO', 768, 228, 'TOGO', 'Togo');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (214, 'TK', 'TKL', 772, 690, 'TOKELAU', 'Tokelau');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (215, 'TO', 'TON', 776, 676, 'TONGA', 'Tonga');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (216, 'TT', 'TTO', 780, 1868, 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (217, 'TN', 'TUN', 788, 216, 'TUNISIA', 'Tunisia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (218, 'TR', 'TUR', 792, 90, 'TURKEY', 'Turkey');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (219, 'TM', 'TKM', 795, 7370, 'TURKMENISTAN', 'Turkmenistan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (220, 'TC', 'TCA', 796, 1649, 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (221, 'TV', 'TUV', 798, 688, 'TUVALU', 'Tuvalu');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (222, 'UG', 'UGA', 800, 256, 'UGANDA', 'Uganda');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (223, 'UA', 'UKR', 804, 380, 'UKRAINE', 'Ukraine');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (224, 'AE', 'ARE', 784, 971, 'UNITED ARAB EMIRATES', 'United Arab Emirates');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (225, 'GB', 'GBR', 826, 44, 'UNITED KINGDOM', 'United Kingdom');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (226, 'US', 'USA', 840, 1, 'UNITED STATES', 'United States');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (227, 'UM', null, null, 1, 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (228, 'UY', 'URY', 858, 598, 'URUGUAY', 'Uruguay');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (229, 'UZ', 'UZB', 860, 998, 'UZBEKISTAN', 'Uzbekistan');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (230, 'VU', 'VUT', 548, 678, 'VANUATU', 'Vanuatu');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (231, 'VE', 'VEN', 862, 58, 'VENEZUELA', 'Venezuela');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (232, 'VN', 'VNM', 704, 84, 'VIET NAM', 'Viet Nam');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (233, 'VG', 'VGB', 92, 1284, 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (234, 'VI', 'VIR', 850, 1340, 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (235, 'WF', 'WLF', 876, 681, 'WALLIS AND FUTUNA', 'Wallis and Futuna');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (236, 'EH', 'ESH', 732, 212, 'WESTERN SAHARA', 'Western Sahara');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (237, 'YE', 'YEM', 887, 967, 'YEMEN', 'Yemen');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (238, 'ZM', 'ZMB', 894, 260, 'ZAMBIA', 'Zambia');
INSERT INTO universities.country (id, iso, iso3, numcode, phonecode, name, nicename) VALUES (239, 'ZW', 'ZWE', 716, 263, 'ZIMBABWE', 'Zimbabwe');
